### ISSUE TITLE
So what is it?

### ISSUE THREAD

**Issue by Paul-PSDigital** [zumba/swiveljs#9]
I saw this mentioned on the description for:
http://2016.sunshinephp.com/talks#feature-flags-are-flawed-lets-make-them-better

However.. i have no idea how/why someone would use this, lil documentation? ;)

**Comment by luispabon** [comment]
Code is self-documented bruv.

**Comment by young-steveo** [comment]
@thepauleh This is a companion project to the main PHP library: https://github.com/zumba/swivel

The readme file there should answer most of your questions.
